package com.myspace.teste;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class testeDO implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "Campo1")
	private java.lang.String campo1;
	@org.kie.api.definition.type.Label(value = "Campo 2")
	private java.lang.String campo2;
	@org.kie.api.definition.type.Label(value = "Campo 3")
	private java.lang.String campo3;
	@org.kie.api.definition.type.Label(value = "Campo 4")
	private java.lang.Integer campo4;
	@org.kie.api.definition.type.Label(value = "Campo 5")
	private java.util.Date campo5;
	@org.kie.api.definition.type.Label(value = "Campo 6")
	private java.lang.Float campo6;
	@org.kie.api.definition.type.Label(value = "Campo 7")
	private java.lang.String campo7;
	@org.kie.api.definition.type.Label(value = "Campo 8")
	private java.lang.String campo8;
	@org.kie.api.definition.type.Label(value = "Campo 9")
	private java.lang.String campo9;
	@org.kie.api.definition.type.Label(value = "Campo 10")
	private java.lang.String campo10;

	public testeDO() {
	}

	public java.lang.String getCampo1() {
		return this.campo1;
	}

	public void setCampo1(java.lang.String campo1) {
		this.campo1 = campo1;
	}

	public java.lang.String getCampo2() {
		return this.campo2;
	}

	public void setCampo2(java.lang.String campo2) {
		this.campo2 = campo2;
	}

	public java.lang.String getCampo3() {
		return this.campo3;
	}

	public void setCampo3(java.lang.String campo3) {
		this.campo3 = campo3;
	}

	public java.lang.Integer getCampo4() {
		return this.campo4;
	}

	public void setCampo4(java.lang.Integer campo4) {
		this.campo4 = campo4;
	}

	public java.util.Date getCampo5() {
		return this.campo5;
	}

	public void setCampo5(java.util.Date campo5) {
		this.campo5 = campo5;
	}

	public java.lang.Float getCampo6() {
		return this.campo6;
	}

	public void setCampo6(java.lang.Float campo6) {
		this.campo6 = campo6;
	}

	public java.lang.String getCampo7() {
		return this.campo7;
	}

	public void setCampo7(java.lang.String campo7) {
		this.campo7 = campo7;
	}

	public java.lang.String getCampo8() {
		return this.campo8;
	}

	public void setCampo8(java.lang.String campo8) {
		this.campo8 = campo8;
	}

	public java.lang.String getCampo9() {
		return this.campo9;
	}

	public void setCampo9(java.lang.String campo9) {
		this.campo9 = campo9;
	}

	public java.lang.String getCampo10() {
		return this.campo10;
	}

	public void setCampo10(java.lang.String campo10) {
		this.campo10 = campo10;
	}

	public testeDO(java.lang.String campo1, java.lang.String campo2,
			java.lang.String campo3, java.lang.Integer campo4,
			java.util.Date campo5, java.lang.Float campo6,
			java.lang.String campo7, java.lang.String campo8,
			java.lang.String campo9, java.lang.String campo10) {
		this.campo1 = campo1;
		this.campo2 = campo2;
		this.campo3 = campo3;
		this.campo4 = campo4;
		this.campo5 = campo5;
		this.campo6 = campo6;
		this.campo7 = campo7;
		this.campo8 = campo8;
		this.campo9 = campo9;
		this.campo10 = campo10;
	}

}